In [3]:
#Analysis the Species of Iris flowers a particular flower belongs to

#Loading the library with Iris dataset
from sklearn.datasets import load_iris

#Loading scikits random forest classifier library
from sklearn.ensemble import RandomForestClassifier

import numpy as np
import pandas as pd
np.random.seed(0)

In [11]:
#Loading the Iris data into an object 'iris'
iris = load_iris()
#this data is not structured yet

#DataFrame
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [19]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [20]:
df.shape

(150, 4)

In [22]:
#Adding a new column for the specis name
df['Species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
#df['Species'] = pd.Categorical.from_codes(iris['target'], iris['target_names'])
#the above line can also be used to add a column
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [24]:
#Creating Test and Train Data
#by randomly assigning 75% of the data with Train label
df['is_train'] = np.random.uniform(0, 1, len(df)) <= 0.75
#For each row(len(df)), we generate a no. b/w 0 and 1.
#If the number is <=0.75, it is assigned a True label
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  is_train  
0  setosa      True  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [26]:
#Creating dataframes with test rows and training rows
train, test = df[df['is_train'] == True], df[df['is_train'] == False]

print('bumber of observations in training data', len(train))
print('bumber of observations in testing data', len(test))
len(test)/(len(df))

bumber of observations in training data 112
bumber of observations in testing data 38


0.25333333333333335

In [29]:
#Create a list of feature column's names
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [31]:
#Converting the class into digits
y = pd.factorize(train['Species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [33]:
#Creating a Random Forest Classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)

clf.fit(train[features], y)
#Training is completed

/home/prithvi/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [34]:
#Validation/Testing our Classifier
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
#Viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[10:20]
#predicted class probabilities of the input

array([[0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 1. , 0. ],
       [0. , 0.2, 0.8]])

In [37]:
#Mapping names of the plants to each of predicted plant class
preds = iris.target_names[clf.predict(test[features])]

#Predicted species for second 10 observations
preds[10:20]

array(['versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica'], dtype='<U10')

In [40]:
test['Species'][10:20]
#comparing with the test data manually

59     versicolor
60     versicolor
65     versicolor
69     versicolor
71     versicolor
73     versicolor
75     versicolor
78     versicolor
90     versicolor
101     virginica
Name: Species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [41]:
#Creating a Confusion Matrix
pd.crosstab(test['Species'], preds, rownames=['Actual species'], colnames = ['Predicted Species'])

#the diagonal represents the no. of actual/accurate predictions
#Accuracy = 37/(37+1)

Predicted Species  setosa  versicolor  virginica
Actual species                                  
setosa                 10           0          0
versicolor              0           9          0
virginica               0           1         18